version: "3.4"
services:
  mail:
    image: boky/postfix
    restart: always
    environment:
      - ALLOWED_SENDER_DOMAINS=mail.${DOMAIN}
    ports:
      - "587:587"
    container_name: "postfix"
    volumes:
      - ./host/keys/:/etc/opendkim/keys
